name: Auto Release ZIP

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create ZIP (exclude .git)
        run: |
          zip -r sob.zip . -x "*.git*" -x ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Auto Release
          files: |
            sob.zip
            notupdate.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  